[[main]]
  name = "Kütüphane"
  pageRef = "library"
  weight = 10

[[main]]
  name = "🎲 Zar"
  url = "/d20/"
  weight = 20

[[main]]
  pre = "github"
  url = "https://github.com/LorePlaying/loreplaying.com"
  weight = 30