[[main]]
  name = "Library"
  pageRef = "library"
  weight = 10

[[main]]
  name = "🎲 Dice"
  pageRef = "d20"
  weight = 20

[[main]]
  pre = "github"
  url = "https://github.com/LorePlaying/loreplaying.com"
  weight = 30
