[[main]]
  name = "📙 Library"
  pageRef = "library"
  weight = 10

[[main]]
  name = "🎲 Dice"
  pageRef = "d20"
  weight = 20

[[main]]
  name = "🗺️ Roadmap"
  pre = "map"
  url = "/roadmap/"
  weight = 30

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/LorePlaying/loreplaying.com"
  weight = 40
